# action.yml
name: "cppcheck and review"
author: myml
branding:
  icon: "check"
  color: "black"
description: "check pull request with cppcheck and post result to review comments"
inputs:
  github_token:
    description: "action github token"
    required: false
  repository:
    description: "owner and repository name"
    required: true
  pull_request_id:
    description: "pull request id"
    required: true
  allow_approve:
    description: "allow submit approve review"
    required: true
    default: true
  enable_checks:
    description: "checks to enable"
    required: true
    default: "all"
  install_cppcheck:
    description: "install cppcheck by apt"
    required: false
    default: true
  comment_result:
    description: "submit the result in a comment"
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - name: install cppcheck
      if: inputs.install_cppcheck == 'true'
      shell: bash
      run: |
        sudo apt-get install -y -q cppcheck
    - name: run cppcheck
      shell: bash
      run: |
        cppcheck --enable=${{ inputs.enable_checks }} --output-file=report.xml --xml .

    - name: install golang
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17.1
    - name: install action-cppcheck
      shell: bash
      run: |
        cd $GITHUB_ACTION_PATH
        go build ./cmd/action-cppcheck
    - name: command
      shell: bash
      run: $GITHUB_ACTION_PATH/action-cppcheck -f=report.xml -repo=${{ inputs.repository }} -pr=${{ inputs.pull_request_id }} -approve=${{ inputs.allow_approve }} -commentResult=${{ inputs.comment_result }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
