# action.yml
name: "cppcheck and review"
author: myml
branding:
  icon: "check"
  color: "black"
description: "check pull request with cppcheck and post result to review comments"
inputs:
  github_token:
    description: "action github token"
    required: false
  repository:
    description: "owner and repository name"
    required: true
  pull_request_id:
    description: "pull request id"
    required: true
  allow_approve:
    description: "allow submit approve review"
    required: true
    default: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.17.1
    - name: run
      shell: bash
      run: |
        sudo apt-get install -y -q cppcheck
        cppcheck --enable=all --output-file=report.xml --xml .
    - name: install action bin
      shell: bash
      run: |
        go env -w GO111MODULE=on GOPROXY=direct,https://proxy.golang.org
        go install github.com/linuxdeepin/action-cppcheck/cmd/action-cppcheck@v0
    - name: command
      shell: bash
      run: action-cppcheck -f=report.xml -repo=${{ inputs.repository }} -pr=${{ inputs.pull_request_id }} -approve=${{ inputs.allow_approve }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
